### ISSUE TITLE
The logs are downloaded instead of displaying on the html report when opening the report on Jenkins.

### ISSUE THREAD

**Issue by yenchenhuang** [TitouanVanBelle/XCTestHTMLReport#147] opened 2019-10-29 09:51 UTC
Hi,

We run our test on Jenkins and the test logs will be downloaded automatically as soon as I open the html report on Jenkins. It shows all blank if switching to the Logs tab in the html report.

The job execute `xchtmlreport -r {XCRESULT}` to generate the html report and will archive the xcresult test output and the html report.

The issue didn't happen when running Xcode 10.1 and XCTestHTMLReport Version 1.6.1. And also 
 the issue wouldn't happen if executing `xchtmlreport -r {XCRESULT}` locally and opening the report.

This probably similar to the issue #145 .

Xcode Version: 11.1
XCTestHTMLReport Version: 2.0.0
Device: iMac (MacOS: 10.14.6)

**Comment by ripunjayasaran** [comment] 2019-10-29 20:41
yeah, this is definitely a dupe of #145

**Comment by gokberkince** [comment] 2020-04-22 15:01
Im also facing the issue too, logs downloading with .dms file instead of showing with html. Could you fix this?

**Comment by nacho4d** [comment] 2021-07-17 03:00
Fix Pull Request https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/201 has been merged. I will close this issue. If problem persists please reopen :)

**Closed** 2021-07-17 03:00 UTC
