### ISSUE TITLE
xchtmlreport[10912:149218] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9'

### ISSUE THREAD

**Issue by anuragmaheshwari** [TitouanVanBelle/XCTestHTMLReport#166] opened 2020-02-07 22:14 UTC
Any idea why it would throw exception while generating XCHTML report

<pre>[---------------------------------------------------
[03:46:00]: --- Step: Switch to ios generateTestReport lane ---
[03:46:00]: ---------------------------------------------------
[03:46:00]: Cruising over to lane 'ios generateTestReport' 🚖
[03:46:01]: Generate a test report using XCTestHTMLReport
[03:46:01]: --------------------------------------------------------------------
[03:46:01]: Step: ../../../buildscripts/xchtmlreport -j -r ./test_output/TextNowSwift-Regression-XCUITests.test_result.xcresult
[03:46:01]: --------------------------------------------------------------------
[03:46:01]: $ ../../../buildscripts/xchtmlreport -j -r ./test_output/TextNowSwift-Regression-XCUITests.test_result.xcresult
[03:48:42]: ▸ 2020-02-07 03:48:42.396 xchtmlreport[10998:155596] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9'
[03:48:42]: ▸ *** First throw call stack:
[03:48:42]: ▸ (
[03:48:42]: ▸ 0   CoreFoundation                      0x00007fff3a4679b3 __exceptionPreprocess + 250
[03:48:42]: ▸ 1   libobjc.A.dylib                     0x00007fff705ec562 objc_exception_throw + 48
[03:48:42]: ▸ 2   Foundation                          0x00007fff3cac6108 -[NSConcreteTask launchWithDictionary:error:] + 5321
[03:48:42]: ▸ 3   xchtmlreport                        0x0000000101001a8f $s11XCResultKit0A4FileC13exportPayload2id10Foundation3URLVSgSS_tF + 831
[03:48:42]: ▸ 4   xchtmlreport                        0x0000000101019da6 $s16XCTestHTMLReport10ResultFileC13exportPayload2id10Foundation3URLVSgSS_tF + 182
[03:48:42]: ▸ 5   xchtmlreport                        0x00000001010125bd $s16XCTestHTMLReport10AttachmentV10attachment4file7paddingAC11XCResultKit010ActionTestC0V_AA10ResultFileCSitcfCTf4nnnd_n + 589
[03:48:42]: ▸ 6   xchtmlreport                        0x0000000101010c8a $s16XCTestHTMLReport8ActivityV7summary4file7paddingAC11XCResultKit010ActionTestC7SummaryV_AA10ResultFileCSitcfCTf4nnnd_n + 1354
[03:48:42]: ▸ 7   xchtmlreport                        0x0000000101010a4c $s16XCTestHTMLReport8ActivityV7summary4file7paddingAC11XCResultKit010ActionTestC7SummaryV_AA10ResultFileCSitcfCTf4nnnd_n + 780
[03:48:42]: ▸ 8   xchtmlreport                        0x000000010102f7ed $s16XCTestHTMLReport4TestV8metadata4fileAC11XCResultKit06ActionC8MetadataV_AA10ResultFileCtcfCTf4nnd_n + 989
[03:48:42]: ▸ 9   xchtmlreport                        0x000000010102fc97 $s16XCTestHTMLReport4TestV5group4fileAC11XCResultKit06ActionC12SummaryGroupV_AA10ResultFileCtcfCTf4nnd_n + 711
[03:48:42]: ▸ 10  xchtmlreport                        0x000000010102fdca $s16XCTestHTMLReport4TestV5group4fileAC11XCResultKit06ActionC12SummaryGroupV_AA10ResultFileCtcfCTf4nnd_n + 1018
[03:48:42]: ▸ 11  xchtmlreport                        0x000000010102fdca $s16XCTestHTMLReport4TestV5group4fileAC11XCResultKit06ActionC12SummaryGroupV_AA10ResultFileCtcfCTf4nnd_n + 1018
[03:48:42]: ▸ 12  xchtmlreport                        0x00000001010328e3 $s16XCTestHTMLReport11TestSummaryV7summary4fileAC11XCResultKit014ActionTestableD0V_AA10ResultFileCtcfCTf4nnd_n + 515
[03:48:42]: ▸ 13  xchtmlreport                        0x0000000101026ff6 $s16XCTestHTMLReport3RunV6action4fileACSg11XCResultKit12ActionRecordV_AA10ResultFileCtcfCTf4nnd_n + 4870
[03:48:42]: ▸ 14  xchtmlreport                        0x000000010102bdcc $s16XCTestHTMLReport7SummaryV11resultPathsACSaySSG_tcfCTf4gd_n + 2108
[03:48:42]: ▸ 15  xchtmlreport                        0x000000010100c300 main + 1376
[03:48:42]: ▸ 16  libdyld.dylib                       0x00007fff719432e5 start + 1
[03:48:42]: ▸ 17  ???                                 0x0000000000000004 0x0 + 4
[03:48:42]: ▸ )
[03:48:42]: ▸ libc++abi.dylib: terminating with uncaught exception of type NSException
[03:48:42]: ▸ XCTestHTMLReport 2.0.0
[03:48:42]: generateTestReport finished with errors]</pre>

**Comment by YesVladess** [comment] 2020-02-18 11:02
Same problem for me, but the error is thrown when generating a 150 cases report.
With 30 cases report works fine.

**Comment by KrzysztofKupczyk** [comment] 2020-02-21 09:46
The same for me, trying to generate report for suit build with 100 test cases

**Comment by kopczyd** [comment] 2020-02-24 08:41
+1
Can't generate a report with more than 100 test cases. Generating small packs work fine, but we don't have small packs in project

**Comment by Kastet** [comment] 2020-02-27 05:06
Same problem here. Has anyone found a solution?

**Comment by krin-san** [comment] 2020-02-27 12:31
The root of this problem goes deeper, from XCResultKit which starts `xcresulttool` to export a file: https://github.com/davidahouse/XCResultKit/blob/5896f470733c13d107fa7262a4be6d1dd443c5c0/Sources/XCResultKit/XCResultFile.swift#L107

The same crash `posix_spawn_file_actions for fd -1 at index 0 with errno 9` happened a LOT with docker because it was opening too many file descriptors without properly closing them.

Could that be a bug in Apple's `xcresulttool` or there's something wrong in `XCResultKit.XCResultFile .xcrun` function?
@davidahouse, maybe you know why that happens?

**Comment by davidahouse** [comment] 2020-02-27 12:53
Looking at the stack trace it is having a problem in the `exportPayload` which is explicitly for pulling out an attachment into a temporary file. So the number of test cases shouldn't matter, but the number of attachments might. Can you confirm if the problem is happening for test runs with lots of attachments? Also, anyone willing to share their xcresult files so I can try locally to debug (or if you have open source projects just post a link here)? I do suspect the `.xcrun` function might have an issue when there are a lot of files. We already made one fix to it, but depending on the situation it still might not be releasing resources fast enough. I'll see what I can do to fix that.

**Comment by davidahouse** [comment] 2020-02-28 14:30
I made a change to the `exportPayload` that might help this issue: https://github.com/davidahouse/XCResultKit/releases/tag/v0.5.6

However, it is still possible that something else is consuming these file descriptors and it was only showing XCResultKit in the stack trace since that is where it ran out. But my fix above should at least help. I'll setup a large project soon so I can test this case more directly and debug in my environment. Keep me posted!

**Comment by krin-san** [comment] 2020-03-02 07:47
@davidahouse, thank you for your effort! Unfortunately I cannot share test results from the closed-source project, but I will try to use your branch with the same amount of devices we had last time.

**Comment by krin-san** [comment] 2020-03-02 10:21
@davidahouse, just tested your new release on 4 devices with 39 test cases = 156 test cases in total. Works flawlessly! Thank you very much for you help.

I will create a PR with a version update soon.

**Comment by samarth220194** [comment] 2020-03-03 05:46
@krin-san Can you please notify when will this issue fix be released on production?

**Closed** 2020-03-03 06:10 UTC

**Comment by krin-san** [comment] 2020-03-03 07:53
@samarth220194, sorry, but I'm not maintaining this repo and therefore cannot provide you with ERD ¯\_(ツ)_/¯

You could subscribe to release notifications with a "Watch" button on top of this or any repo page.

**Comment by samarth220194** [comment] 2020-03-03 07:55
@krin-san thanks

**Comment by krin-san** [comment] 2020-06-22 08:12
After an extensive debugging performed for this issue again _(because I didn't realized I was not using `--HEAD` with `brew install`)_ I found how to prove this fix actually works.

When installing 2.0.0 tagged release, `xchtmlreport` leaks PIPE descriptors each time it was exporting a new screenshot. That can be observed with the following command:
```
lsof -a -p $(pgrep xchtmlreport)
```
and looks like that:
```
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF                NODE NAME
xchtmlrep 27171 gitlab  cwd    DIR                1,7     1376         13007060645 /Users/gitlab/builds/...
xchtmlrep 27171 gitlab  twd    DIR                1,7     1376         13007060645 /Users/gitlab/builds/...
xchtmlrep 27171 gitlab  txt    REG                1,7  1581592         13061032217 /usr/local/Cellar/xchtmlreport/2.0.0/bin/xchtmlreport
xchtmlrep 27171 gitlab  txt    REG                1,7    28420         13041424654 /Library/Preferences/Logging/.plist-cache.dpuvuDL7
xchtmlrep 27171 gitlab  txt    REG                1,7 28484912 1152921500312484554 /usr/share/icu/icudt64l.dat
xchtmlrep 27171 gitlab  txt    REG                1,7   240192         13036751661 /private/var/db/timezone/tz/2020a.1.0/icutz/icutz44l.dat
xchtmlrep 27171 gitlab  txt    REG                1,7  1568368 1152921500312483143 /usr/lib/dyld
xchtmlrep 27171 gitlab    0   PIPE 0x3ebfeacd85f551a0    16384                     
xchtmlrep 27171 gitlab    1   PIPE 0x7ba89a788464d458    16384                     ->0xbb74b0c74af069a6
xchtmlrep 27171 gitlab    2   PIPE 0x7ba89a788464d458    16384                     ->0xbb74b0c74af069a6
xchtmlrep 27171 gitlab    3   PIPE 0x458b0ee9b885aa3e    65536                     
...
xchtmlrep 27171 gitlab 2455   PIPE 0xc0613fa820a74608    16384                     
xchtmlrep 27171 gitlab 2456   PIPE 0xfc83041804781dae    16384                     ->0x664fcd0531b96c11
```
All pipes with FD 3-2455 have no value in NAME field which is probably a pointer to `Task` or `Pipe` object which uses it. It just leaks. And once it leaks around 2500-2600 descriptors _(`ulimit -a` returns `2560`)_, OS refuses to create a new descriptor and app crashes.

And that don't happen if `xchtmlreport` is installed from `develop` with `brew install --HEAD`.

**Comment by deepjyot** [comment] 2020-10-07 11:55
I am also facing this crash: 'Failed to set posix_spawn_file_actions for fd -1 at index 1 with errno 9' 
Pl help
