### ISSUE TITLE
brew not working

### ISSUE THREAD

**Issue by maxelrod** [TitouanVanBelle/XCTestHTMLReport#87] opened 2018-06-09 18:16 UTC
```
MARAXELR-M-C1HN:slaveconfig maraxelr$ brew install TitouanVanBelle/XCTestHTMLReport/xchtmlreport
Error: No available formula with the name "titouanvanbelle/xctesthtmlreport/xchtmlreport" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
MARAXELR-M-C1HN:slaveconfig maraxelr$ brew install --HEAD TitouanVanBelle/XCTestHTMLReport/xchtmlreport
Error: No available formula with the name "titouanvanbelle/xctesthtmlreport/xchtmlreport" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
MARAXELR-M-C1HN:slaveconfig maraxelr$

**Comment by maxelrod** [comment] 2018-06-09 18:17
These are commands pasted straight from project `README.md`

**Comment by TitouanVanBelle** [comment] 2018-06-09 19:03
Closing. Duplicate of #86

**Closed by TitouanVanBelle** 2018-06-09 19:03 UTC
